### ISSUE TITLE
Consider moving the code generator back to simphony-common

### ISSUE THREAD

**Issue by kitchoi** [simphony/simphony-metadata#39]

**Comment by stefanoborini** [comment]
@mehdisadeghi Where is the code generator supposed to be? I suspect it should be in simphony-metadata, so that when the metadata files change in a non-backward compatible way, the generator follow in the change. 

Right now we have two copies of the generator, one in simphony-metadata, and another in simphony-common. One must go. Which one?

**Comment by mehdisadeghi** [comment]
@stefanoborini previously with @kitchoi we discussed this and decided to move it back to simphony-common. However, the problem of running tests upon changes to metadata remains unaddressed.

**Comment by stefanoborini** [comment]
@mehdisadeghi ok which means that the copy currently in simphony-metadata is not supposed to be there. For the tests, when the metadata automatic build will be merged, we will always run against the most recent commit of the metadata.

**Comment by mehdisadeghi** [comment]
> which means that the copy currently in simphony-metadata is not supposed to be there

There is a PR #49 for that. However, we still need to add a YAML and schema validator to this repo.

**Comment by mehdisadeghi** [comment]
Done in #49
